name: Cancel currently running CI workflows
on:
  workflow_run:
    workflows: ['CI']
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa #v0.12.1
        with:
          ignore_sha: true
          workflow_id: ${{ github.event.workflow.id }}
