name: 'CI'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn install
      - name: Check for uncommitted changes in yarn.lock
        run: |
          if git diff --name-only | grep -q "^yarn.lock"; then
            echo "::error::The yarn.lock file has uncommitted changes!"
            exit 1
          fi
  lint:
    name: Lint
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 18.x
      - name: Install
        run: |
          yarn install --ignore-scripts
          yarn compile
      - name: Create eslint json report
        run: |
          yarn lint:ci
        continue-on-error: true
      - name: Create summary
        run: |
          npm_config_yes=true npx github:10up/eslint-json-to-md#82ff16b --path ./eslint_report.json --output ./eslint_report.md
          cat eslint_report.md >> $GITHUB_STEP_SUMMARY

  playwright:
    name: Playwright Tests
    timeout-minutes: 120
    runs-on: ubuntu-latest
    env:
      STANDALONE_URL: 'file://${{ github.workspace }}/examples/workflow-test/repositories/glsp-client/examples/workflow-standalone/app/diagram.html'
      THEIA_URL: 'http://localhost:3000'
      VSCODE_VSIX_ID: 'eclipse-glsp.workflow-vscode-example'
      VSCODE_VSIX_PATH: '${{ github.workspace }}/examples/workflow-test/repositories/glsp-vscode-integration/example/workflow/extension/workflow-vscode-example-2.2.0-next.vsix'
      GLSP_SERVER_DEBUG: 'true'
      GLSP_SERVER_PORT: '8081'
      GLSP_SERVER_PLAYWRIGHT_MANAGED: 'true'
      GLSP_WEBSOCKET_PATH: 'workflow'

    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn install
      - name: Prepare repos
        run: yarn repo prepare --protocol https
      - name: Start theia
        run: yarn repo theia-integration start &
      - name: Run Playwright tests
        run: xvfb-run -a yarn test
        continue-on-error: true
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4.3.4
        with:
          name: playwright-report
          path: examples/workflow-test/playwright-report/
