name: E2E Playwright Tests (Multi OS)

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '20 18 * * 1'

jobs:
  playwright-node:
    name: E2E Playwright (Node)
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, ubuntu-latest, macos-14]
    timeout-minutes: 120
    runs-on: ${{ matrix.os }}
    env:
      THEIA_URL: 'http://localhost:3000'
      VSCODE_VSIX_ID: 'eclipse-glsp.workflow-vscode-example'
      GLSP_SERVER_DEBUG: 'true'
      GLSP_SERVER_PORT: '8081'
      GLSP_SERVER_PLAYWRIGHT_MANAGED: 'true'
      GLSP_WEBSOCKET_PATH: 'workflow'
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn install
      - name: Prepare repos
        run: yarn repo prepare --protocol https
      - name: Set Environment Variables
        run: |
          echo "STANDALONE_URL=$(yarn -s repo client url)" >> $GITHUB_ENV
          echo "VSCODE_VSIX_PATH=$(yarn -s repo vscode-integration vsixPath)" >> $GITHUB_ENV
          echo "GLSP_SERVER_START_COMMAND=yarn repo node-server start" >> $GITHUB_ENV
      - name: Start theia
        run: yarn repo theia-integration start &
      - name: Run Playwright tests
        id: run_playwright_tests
        run: |
          if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            xvfb-run -a yarn test
          else
             yarn test
          fi
      - name: Upload Playwright report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4.3.4
        with:
          name: playwright-report-${{ matrix.os }}
          path: examples/workflow-test/playwright-report/
