name: E2E Playwright Tests (Multi OS)

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '20 18 * * 1' # At 18:20 on Monday

jobs:
  playwright-node:
    name: E2E Playwright (Node)
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, ubuntu-22.04, macos-14]
    timeout-minutes: 120
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: '22'
      - name: Install dependencies
        run: yarn install
      - name: Prepare repos
        run: yarn repo:setup
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Run Playwright tests
        id: run_playwright_tests
        run: |
          if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            xvfb-run -a yarn test
          else
             yarn test
          fi
      - name: Upload Playwright report
        if: ${{ always() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: playwright-report-${{ matrix.os }}
          path: examples/workflow-test/playwright-report/
